services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=meetingScheduler
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
